// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCib: youtube': typeof import('~icons/cib/youtube')['default']
    'IconCib:amazon': typeof import('~icons/cib/amazon')['default']
    'IconCib:appleMusic': typeof import('~icons/cib/apple-music')['default']
    'IconCib:deezer': typeof import('~icons/cib/deezer')['default']
    'IconCib:instagram': typeof import('~icons/cib/instagram')['default']
    'IconCib:spotify': typeof import('~icons/cib/spotify')['default']
    'IconCib:youtube': typeof import('~icons/cib/youtube')['default']
    IconFaSolid: ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    IconLa: language': typeof import('~icons/la/language')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    IconUil: times': typeof import('~icons/uil/times')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
